/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import JFrame.AlertaBien;
import JFrame.AlertaError;
import Metodos.Contactos.Contacto;
import Metodos.Contactos.GrupoContactos;
//import Metodos.Sonidos;
import Validaciones.ValidarDatos;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

/**
 *
 * @author luisg
 */
public class AgregarContacto extends javax.swing.JFrame implements Serializable{

    GrupoContactos grupoContactos;
    Contacto nuevoContacto;
    Contacto[] contactos;
    ValidarDatos valido = new ValidarDatos();
    AlertaError ae;
    AlertaBien ab;
//    Sonidos music;
    int nUsuario = 0;
    public AgregarContacto() {
        
    }

    public AgregarContacto(GrupoContactos grupoContactos, JComboBox<String> jComboBox_Grupos, int nUsuario) {
        initComponents();
        iniciar(jComboBox_Grupos);
        this.grupoContactos = grupoContactos;
        this.nUsuario = nUsuario;
        this.setTitle("Agregar Contacto");
        setIconImage(new ImageIcon(getClass().getResource("/Images/Logo_Oso124x128.png")).getImage());
    }

    public void iniciar(JComboBox<String> jComboBox_Grupos) {
        setLocationRelativeTo(null);
//        music = new Sonidos();

        for (int i = 0; i < jComboBox_Grupos.getItemCount(); i++) {
            String grupos;
            grupos = jComboBox_Grupos.getItemAt(i);
            bxGrupos.addItem(grupos);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        newTelefono = new javax.swing.JTextField();
        newNombre = new javax.swing.JTextField();
        newCorreo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        bxGrupos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel3.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AGREGA TU CONTACTO");

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefono");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Correo");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 130, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nombre");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, -1));
        jPanel7.add(newTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 130, -1));
        jPanel7.add(newNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, -1));
        jPanel7.add(newCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 170, -1));

        btnAgregar.setBackground(new java.awt.Color(204, 204, 204));
        btnAgregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        bxGrupos.setBackground(new java.awt.Color(102, 0, 0));
        bxGrupos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bxGrupos.setForeground(new java.awt.Color(255, 255, 255));
        bxGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxGruposActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ej. 0123456789");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ej. Usuario");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seleccione el grupo");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ej. example@gmail.com");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Todo.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(600, 400));
        jLabel2.setMinimumSize(new java.awt.Dimension(600, 400));
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel8)
                .addGap(319, 319, 319)
                .addComponent(jLabel7))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel10))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(bxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnAgregar))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel9))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(61, 61, 61)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(bxGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = newNombre.getText();
        String correo = newCorreo.getText();
        String telefono = newTelefono.getText();

        boolean ValeNombre = valido.validarNombre(nombre);
        boolean ValeCorreo = valido.validarCorreo(correo);
        boolean ValeTelefono = valido.validarTelefono(telefono);

        if (nombre.equals("")) {
//            music.musicaError();
            ae = new AlertaError("El campo del Nombre esta vacio", "");
            ae.setVisible(true);
        } else if (telefono.equals("")) {
//            music.musicaError();
            ae = new AlertaError("El campo del Telefono esta vacio", "");
            ae.setVisible(true);
        } else if (ValeNombre == false) {
//            music.musicaError();
            ae = new AlertaError("El nombre ingresado no es valido", "El nombre comienza con Mayuscula");
            ae.setVisible(true);
        } else if (ValeCorreo == false) {
//            music.musicaError();
            ae = new AlertaError("El correo ingresado no es valido", "El correo debe cumplir con la denominacion estandar de @ y .com");
            ae.setVisible(true);
        } else if (ValeTelefono == false) {
//            music.musicaError();
            ae = new AlertaError("El telefono ingresado no es valido", "El numero de telefono debe contener 10 digitos");
            ae.setVisible(true);
        } else {

            int nGrupo;
            nGrupo = bxGrupos.getSelectedIndex();

            nuevoContacto = new Contacto(nGrupo, nombre, correo, telefono,nUsuario);
            System.out.println(nuevoContacto.toString());
            
            boolean  nomRepetido = grupoContactos.repetido(nuevoContacto, nombre);

            if(nomRepetido == false){
                grupoContactos.añadirContacto(nuevoContacto);
                System.out.println(grupoContactos.imprimirContactos());
                ab = new AlertaBien("El contacto fue exitosamente ingresado", "");
                ab.setVisible(true);
                newNombre.setText("");
                newCorreo.setText("");
                newTelefono.setText(""); 
            }else{
//                music.musicaError();
                ae = new AlertaError("El nombre de contacto repetido", "");
                ae.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void bxGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxGruposActionPerformed
        // COMBO BOX Acciones para elegir

    }//GEN-LAST:event_bxGruposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> bxGrupos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField newCorreo;
    private javax.swing.JTextField newNombre;
    private javax.swing.JTextField newTelefono;
    // End of variables declaration//GEN-END:variables
}
